global:
  scrape_interval: 15s

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter — host metrics
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  # cAdvisor — container-level metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
